[package]
name = "telemetrydeck-cli-example"
version = "0.1.0"
edition = "2021"

[dependencies]
telemetrydeck-wasm = { path = "../.." }
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.48", features = ["full"] }
