name: Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  native_tests:
    name: Native Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-native-tests-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-doc-tests-
            cargo-${{ runner.os }}-
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
