name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  native_tests:
    name: Native Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target
          key: cargo-${{ runner.os }}-native-tests-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-doc-tests-
            cargo-${{ runner.os }}-

      - name: Run tests
        run: cargo test --all
